/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BecomeARiderRouteImport } from './routes/become-a-rider'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RiderIndexRouteImport } from './routes/rider.index'
import { Route as PackagesIndexRouteImport } from './routes/packages.index'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RiderProfileRouteImport } from './routes/rider.profile'
import { Route as RiderHistoryRouteImport } from './routes/rider.history'
import { Route as PayBookingIdRouteImport } from './routes/pay.$bookingId'
import { Route as PackagesIdRouteImport } from './routes/packages.$id'
import { Route as PackageIdRouteImport } from './routes/package.$id'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'
import { Route as BookPackageIdRouteImport } from './routes/book.$packageId'
import { Route as AppWaitingListRouteImport } from './routes/app.waiting-list'
import { Route as AppPromosRouteImport } from './routes/app.promos'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppPackagesRouteImport } from './routes/app.packages'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AdminWaitingListRouteImport } from './routes/admin.waiting-list'
import { Route as AdminVehicleTypesRouteImport } from './routes/admin.vehicle-types'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTripsRouteImport } from './routes/admin.trips'
import { Route as AdminSosRouteImport } from './routes/admin.sos'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRoutesRouteImport } from './routes/admin.routes'
import { Route as AdminRidersRouteImport } from './routes/admin.riders'
import { Route as AdminRiderApplicationsRouteImport } from './routes/admin.rider-applications'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPromosRouteImport } from './routes/admin.promos'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminNotificationsCenterRouteImport } from './routes/admin.notifications-center'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminHubsRouteImport } from './routes/admin.hubs'
import { Route as AdminHubAdminsRouteImport } from './routes/admin.hub-admins'
import { Route as AdminCheckinRouteImport } from './routes/admin.checkin'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AppBookingsIndexRouteImport } from './routes/app.bookings.index'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin.bookings.index'
import { Route as RiderToursIdRouteImport } from './routes/rider.tours.$id'
import { Route as AppPackagesSlugRouteImport } from './routes/app.packages.$slug'
import { Route as AppCategorySlugRouteImport } from './routes/app.category.$slug'
import { Route as AppBookingsIdRouteImport } from './routes/app.bookings.$id'
import { Route as AppBookPackageIdRouteImport } from './routes/app.book.$packageId'
import { Route as AdminBookingsIdRouteImport } from './routes/admin.bookings.$id'

const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeARiderRoute = BecomeARiderRouteImport.update({
  id: '/become-a-rider',
  path: '/become-a-rider',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RiderRoute,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RiderProfileRoute = RiderProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RiderRoute,
} as any)
const RiderHistoryRoute = RiderHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => RiderRoute,
} as any)
const PayBookingIdRoute = PayBookingIdRouteImport.update({
  id: '/pay/$bookingId',
  path: '/pay/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIdRoute = PackagesIdRouteImport.update({
  id: '/packages/$id',
  path: '/packages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIdRoute = PackageIdRouteImport.update({
  id: '/package/$id',
  path: '/package/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookPackageIdRoute = BookPackageIdRouteImport.update({
  id: '/book/$packageId',
  path: '/book/$packageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWaitingListRoute = AppWaitingListRouteImport.update({
  id: '/waiting-list',
  path: '/waiting-list',
  getParentRoute: () => AppRoute,
} as any)
const AppPromosRoute = AppPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesRoute = AppPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AdminWaitingListRoute = AdminWaitingListRouteImport.update({
  id: '/waiting-list',
  path: '/waiting-list',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehicleTypesRoute = AdminVehicleTypesRouteImport.update({
  id: '/vehicle-types',
  path: '/vehicle-types',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTripsRoute = AdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSosRoute = AdminSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoutesRoute = AdminRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRidersRoute = AdminRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRiderApplicationsRoute = AdminRiderApplicationsRouteImport.update({
  id: '/rider-applications',
  path: '/rider-applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromosRoute = AdminPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsCenterRoute =
  AdminNotificationsCenterRouteImport.update({
    id: '/notifications-center',
    path: '/notifications-center',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHubsRoute = AdminHubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHubAdminsRoute = AdminHubAdminsRouteImport.update({
  id: '/hub-admins',
  path: '/hub-admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckinRoute = AdminCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AppBookingsIndexRoute = AppBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AppRoute,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRoute,
} as any)
const RiderToursIdRoute = RiderToursIdRouteImport.update({
  id: '/tours/$id',
  path: '/tours/$id',
  getParentRoute: () => RiderRoute,
} as any)
const AppPackagesSlugRoute = AppPackagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppPackagesRoute,
} as any)
const AppCategorySlugRoute = AppCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsIdRoute = AppBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBookPackageIdRoute = AppBookPackageIdRouteImport.update({
  id: '/book/$packageId',
  path: '/book/$packageId',
  getParentRoute: () => AppRoute,
} as any)
const AdminBookingsIdRoute = AdminBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-a-rider': typeof BecomeARiderRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rider': typeof RiderRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/hub-admins': typeof AdminHubAdminsRoute
  '/admin/hubs': typeof AdminHubsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/notifications-center': typeof AdminNotificationsCenterRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rider-applications': typeof AdminRiderApplicationsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sos': typeof AdminSosRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicle-types': typeof AdminVehicleTypesRoute
  '/admin/waiting-list': typeof AdminWaitingListRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/packages': typeof AppPackagesRouteWithChildren
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/promos': typeof AppPromosRoute
  '/app/waiting-list': typeof AppWaitingListRoute
  '/book/$packageId': typeof BookPackageIdRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/package/$id': typeof PackageIdRoute
  '/packages/$id': typeof PackagesIdRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/rider/history': typeof RiderHistoryRoute
  '/rider/profile': typeof RiderProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/app/book/$packageId': typeof AppBookPackageIdRoute
  '/app/bookings/$id': typeof AppBookingsIdRoute
  '/app/category/$slug': typeof AppCategorySlugRoute
  '/app/packages/$slug': typeof AppPackagesSlugRoute
  '/rider/tours/$id': typeof RiderToursIdRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/app/bookings/': typeof AppBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-a-rider': typeof BecomeARiderRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/hub-admins': typeof AdminHubAdminsRoute
  '/admin/hubs': typeof AdminHubsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/notifications-center': typeof AdminNotificationsCenterRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rider-applications': typeof AdminRiderApplicationsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sos': typeof AdminSosRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicle-types': typeof AdminVehicleTypesRoute
  '/admin/waiting-list': typeof AdminWaitingListRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/packages': typeof AppPackagesRouteWithChildren
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/promos': typeof AppPromosRoute
  '/app/waiting-list': typeof AppWaitingListRoute
  '/book/$packageId': typeof BookPackageIdRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/package/$id': typeof PackageIdRoute
  '/packages/$id': typeof PackagesIdRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/rider/history': typeof RiderHistoryRoute
  '/rider/profile': typeof RiderProfileRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/packages': typeof PackagesIndexRoute
  '/rider': typeof RiderIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/app/book/$packageId': typeof AppBookPackageIdRoute
  '/app/bookings/$id': typeof AppBookingsIdRoute
  '/app/category/$slug': typeof AppCategorySlugRoute
  '/app/packages/$slug': typeof AppPackagesSlugRoute
  '/rider/tours/$id': typeof RiderToursIdRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/app/bookings': typeof AppBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-a-rider': typeof BecomeARiderRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rider': typeof RiderRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/hub-admins': typeof AdminHubAdminsRoute
  '/admin/hubs': typeof AdminHubsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/notifications-center': typeof AdminNotificationsCenterRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rider-applications': typeof AdminRiderApplicationsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sos': typeof AdminSosRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicle-types': typeof AdminVehicleTypesRoute
  '/admin/waiting-list': typeof AdminWaitingListRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/packages': typeof AppPackagesRouteWithChildren
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/promos': typeof AppPromosRoute
  '/app/waiting-list': typeof AppWaitingListRoute
  '/book/$packageId': typeof BookPackageIdRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/package/$id': typeof PackageIdRoute
  '/packages/$id': typeof PackagesIdRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/rider/history': typeof RiderHistoryRoute
  '/rider/profile': typeof RiderProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/app/book/$packageId': typeof AppBookPackageIdRoute
  '/app/bookings/$id': typeof AppBookingsIdRoute
  '/app/category/$slug': typeof AppCategorySlugRoute
  '/app/packages/$slug': typeof AppPackagesSlugRoute
  '/rider/tours/$id': typeof RiderToursIdRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/app/bookings/': typeof AppBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/become-a-rider'
    | '/login'
    | '/register'
    | '/rider'
    | '/admin/audit'
    | '/admin/checkin'
    | '/admin/hub-admins'
    | '/admin/hubs'
    | '/admin/locations'
    | '/admin/notifications-center'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/rider-applications'
    | '/admin/riders'
    | '/admin/routes'
    | '/admin/settings'
    | '/admin/sos'
    | '/admin/trips'
    | '/admin/users'
    | '/admin/vehicle-types'
    | '/admin/waiting-list'
    | '/app/notifications'
    | '/app/packages'
    | '/app/payments'
    | '/app/profile'
    | '/app/promos'
    | '/app/waiting-list'
    | '/book/$packageId'
    | '/bookings/$id'
    | '/package/$id'
    | '/packages/$id'
    | '/pay/$bookingId'
    | '/rider/history'
    | '/rider/profile'
    | '/admin/'
    | '/app/'
    | '/bookings/'
    | '/packages/'
    | '/rider/'
    | '/admin/bookings/$id'
    | '/app/book/$packageId'
    | '/app/bookings/$id'
    | '/app/category/$slug'
    | '/app/packages/$slug'
    | '/rider/tours/$id'
    | '/admin/bookings/'
    | '/app/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/become-a-rider'
    | '/login'
    | '/register'
    | '/admin/audit'
    | '/admin/checkin'
    | '/admin/hub-admins'
    | '/admin/hubs'
    | '/admin/locations'
    | '/admin/notifications-center'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/rider-applications'
    | '/admin/riders'
    | '/admin/routes'
    | '/admin/settings'
    | '/admin/sos'
    | '/admin/trips'
    | '/admin/users'
    | '/admin/vehicle-types'
    | '/admin/waiting-list'
    | '/app/notifications'
    | '/app/packages'
    | '/app/payments'
    | '/app/profile'
    | '/app/promos'
    | '/app/waiting-list'
    | '/book/$packageId'
    | '/bookings/$id'
    | '/package/$id'
    | '/packages/$id'
    | '/pay/$bookingId'
    | '/rider/history'
    | '/rider/profile'
    | '/admin'
    | '/app'
    | '/bookings'
    | '/packages'
    | '/rider'
    | '/admin/bookings/$id'
    | '/app/book/$packageId'
    | '/app/bookings/$id'
    | '/app/category/$slug'
    | '/app/packages/$slug'
    | '/rider/tours/$id'
    | '/admin/bookings'
    | '/app/bookings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/become-a-rider'
    | '/login'
    | '/register'
    | '/rider'
    | '/admin/audit'
    | '/admin/checkin'
    | '/admin/hub-admins'
    | '/admin/hubs'
    | '/admin/locations'
    | '/admin/notifications-center'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/rider-applications'
    | '/admin/riders'
    | '/admin/routes'
    | '/admin/settings'
    | '/admin/sos'
    | '/admin/trips'
    | '/admin/users'
    | '/admin/vehicle-types'
    | '/admin/waiting-list'
    | '/app/notifications'
    | '/app/packages'
    | '/app/payments'
    | '/app/profile'
    | '/app/promos'
    | '/app/waiting-list'
    | '/book/$packageId'
    | '/bookings/$id'
    | '/package/$id'
    | '/packages/$id'
    | '/pay/$bookingId'
    | '/rider/history'
    | '/rider/profile'
    | '/admin/'
    | '/app/'
    | '/bookings/'
    | '/packages/'
    | '/rider/'
    | '/admin/bookings/$id'
    | '/app/book/$packageId'
    | '/app/bookings/$id'
    | '/app/category/$slug'
    | '/app/packages/$slug'
    | '/rider/tours/$id'
    | '/admin/bookings/'
    | '/app/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  BecomeARiderRoute: typeof BecomeARiderRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RiderRoute: typeof RiderRouteWithChildren
  BookPackageIdRoute: typeof BookPackageIdRoute
  BookingsIdRoute: typeof BookingsIdRoute
  PackageIdRoute: typeof PackageIdRoute
  PackagesIdRoute: typeof PackagesIdRoute
  PayBookingIdRoute: typeof PayBookingIdRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-rider': {
      id: '/become-a-rider'
      path: '/become-a-rider'
      fullPath: '/become-a-rider'
      preLoaderRoute: typeof BecomeARiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/': {
      id: '/rider/'
      path: '/'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof RiderRoute
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rider/profile': {
      id: '/rider/profile'
      path: '/profile'
      fullPath: '/rider/profile'
      preLoaderRoute: typeof RiderProfileRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/history': {
      id: '/rider/history'
      path: '/history'
      fullPath: '/rider/history'
      preLoaderRoute: typeof RiderHistoryRouteImport
      parentRoute: typeof RiderRoute
    }
    '/pay/$bookingId': {
      id: '/pay/$bookingId'
      path: '/pay/$bookingId'
      fullPath: '/pay/$bookingId'
      preLoaderRoute: typeof PayBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$id': {
      id: '/packages/$id'
      path: '/packages/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof PackagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/$id': {
      id: '/package/$id'
      path: '/package/$id'
      fullPath: '/package/$id'
      preLoaderRoute: typeof PackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$packageId': {
      id: '/book/$packageId'
      path: '/book/$packageId'
      fullPath: '/book/$packageId'
      preLoaderRoute: typeof BookPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/waiting-list': {
      id: '/app/waiting-list'
      path: '/waiting-list'
      fullPath: '/app/waiting-list'
      preLoaderRoute: typeof AppWaitingListRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/promos': {
      id: '/app/promos'
      path: '/promos'
      fullPath: '/app/promos'
      preLoaderRoute: typeof AppPromosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/packages': {
      id: '/app/packages'
      path: '/packages'
      fullPath: '/app/packages'
      preLoaderRoute: typeof AppPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/waiting-list': {
      id: '/admin/waiting-list'
      path: '/waiting-list'
      fullPath: '/admin/waiting-list'
      preLoaderRoute: typeof AdminWaitingListRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehicle-types': {
      id: '/admin/vehicle-types'
      path: '/vehicle-types'
      fullPath: '/admin/vehicle-types'
      preLoaderRoute: typeof AdminVehicleTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trips': {
      id: '/admin/trips'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sos': {
      id: '/admin/sos'
      path: '/sos'
      fullPath: '/admin/sos'
      preLoaderRoute: typeof AdminSosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/routes': {
      id: '/admin/routes'
      path: '/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AdminRoutesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/riders': {
      id: '/admin/riders'
      path: '/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AdminRidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rider-applications': {
      id: '/admin/rider-applications'
      path: '/rider-applications'
      fullPath: '/admin/rider-applications'
      preLoaderRoute: typeof AdminRiderApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promos': {
      id: '/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AdminPromosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications-center': {
      id: '/admin/notifications-center'
      path: '/notifications-center'
      fullPath: '/admin/notifications-center'
      preLoaderRoute: typeof AdminNotificationsCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hubs': {
      id: '/admin/hubs'
      path: '/hubs'
      fullPath: '/admin/hubs'
      preLoaderRoute: typeof AdminHubsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hub-admins': {
      id: '/admin/hub-admins'
      path: '/hub-admins'
      fullPath: '/admin/hub-admins'
      preLoaderRoute: typeof AdminHubAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/checkin': {
      id: '/admin/checkin'
      path: '/checkin'
      fullPath: '/admin/checkin'
      preLoaderRoute: typeof AdminCheckinRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/bookings/': {
      id: '/app/bookings/'
      path: '/bookings'
      fullPath: '/app/bookings/'
      preLoaderRoute: typeof AppBookingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rider/tours/$id': {
      id: '/rider/tours/$id'
      path: '/tours/$id'
      fullPath: '/rider/tours/$id'
      preLoaderRoute: typeof RiderToursIdRouteImport
      parentRoute: typeof RiderRoute
    }
    '/app/packages/$slug': {
      id: '/app/packages/$slug'
      path: '/$slug'
      fullPath: '/app/packages/$slug'
      preLoaderRoute: typeof AppPackagesSlugRouteImport
      parentRoute: typeof AppPackagesRoute
    }
    '/app/category/$slug': {
      id: '/app/category/$slug'
      path: '/category/$slug'
      fullPath: '/app/category/$slug'
      preLoaderRoute: typeof AppCategorySlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings/$id': {
      id: '/app/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/app/bookings/$id'
      preLoaderRoute: typeof AppBookingsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/book/$packageId': {
      id: '/app/book/$packageId'
      path: '/book/$packageId'
      fullPath: '/app/book/$packageId'
      preLoaderRoute: typeof AppBookPackageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/bookings/$id': {
      id: '/admin/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AdminBookingsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCheckinRoute: typeof AdminCheckinRoute
  AdminHubAdminsRoute: typeof AdminHubAdminsRoute
  AdminHubsRoute: typeof AdminHubsRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminNotificationsCenterRoute: typeof AdminNotificationsCenterRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPromosRoute: typeof AdminPromosRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRiderApplicationsRoute: typeof AdminRiderApplicationsRoute
  AdminRidersRoute: typeof AdminRidersRoute
  AdminRoutesRoute: typeof AdminRoutesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSosRoute: typeof AdminSosRoute
  AdminTripsRoute: typeof AdminTripsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVehicleTypesRoute: typeof AdminVehicleTypesRoute
  AdminWaitingListRoute: typeof AdminWaitingListRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBookingsIdRoute: typeof AdminBookingsIdRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCheckinRoute: AdminCheckinRoute,
  AdminHubAdminsRoute: AdminHubAdminsRoute,
  AdminHubsRoute: AdminHubsRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminNotificationsCenterRoute: AdminNotificationsCenterRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPromosRoute: AdminPromosRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRiderApplicationsRoute: AdminRiderApplicationsRoute,
  AdminRidersRoute: AdminRidersRoute,
  AdminRoutesRoute: AdminRoutesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSosRoute: AdminSosRoute,
  AdminTripsRoute: AdminTripsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVehicleTypesRoute: AdminVehicleTypesRoute,
  AdminWaitingListRoute: AdminWaitingListRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBookingsIdRoute: AdminBookingsIdRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppPackagesRouteChildren {
  AppPackagesSlugRoute: typeof AppPackagesSlugRoute
}

const AppPackagesRouteChildren: AppPackagesRouteChildren = {
  AppPackagesSlugRoute: AppPackagesSlugRoute,
}

const AppPackagesRouteWithChildren = AppPackagesRoute._addFileChildren(
  AppPackagesRouteChildren,
)

interface AppRouteChildren {
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPackagesRoute: typeof AppPackagesRouteWithChildren
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPromosRoute: typeof AppPromosRoute
  AppWaitingListRoute: typeof AppWaitingListRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBookPackageIdRoute: typeof AppBookPackageIdRoute
  AppBookingsIdRoute: typeof AppBookingsIdRoute
  AppCategorySlugRoute: typeof AppCategorySlugRoute
  AppBookingsIndexRoute: typeof AppBookingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNotificationsRoute: AppNotificationsRoute,
  AppPackagesRoute: AppPackagesRouteWithChildren,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProfileRoute: AppProfileRoute,
  AppPromosRoute: AppPromosRoute,
  AppWaitingListRoute: AppWaitingListRoute,
  AppIndexRoute: AppIndexRoute,
  AppBookPackageIdRoute: AppBookPackageIdRoute,
  AppBookingsIdRoute: AppBookingsIdRoute,
  AppCategorySlugRoute: AppCategorySlugRoute,
  AppBookingsIndexRoute: AppBookingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface RiderRouteChildren {
  RiderHistoryRoute: typeof RiderHistoryRoute
  RiderProfileRoute: typeof RiderProfileRoute
  RiderIndexRoute: typeof RiderIndexRoute
  RiderToursIdRoute: typeof RiderToursIdRoute
}

const RiderRouteChildren: RiderRouteChildren = {
  RiderHistoryRoute: RiderHistoryRoute,
  RiderProfileRoute: RiderProfileRoute,
  RiderIndexRoute: RiderIndexRoute,
  RiderToursIdRoute: RiderToursIdRoute,
}

const RiderRouteWithChildren = RiderRoute._addFileChildren(RiderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  BecomeARiderRoute: BecomeARiderRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RiderRoute: RiderRouteWithChildren,
  BookPackageIdRoute: BookPackageIdRoute,
  BookingsIdRoute: BookingsIdRoute,
  PackageIdRoute: PackageIdRoute,
  PackagesIdRoute: PackagesIdRoute,
  PayBookingIdRoute: PayBookingIdRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  PackagesIndexRoute: PackagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
